"""
Created at 11/07/20
@author: virenderkumarbhargav
"""
CONST_USER_TYPE = (
    ('vendor', 'vendor'),
    ('owner', 'owner'),
    ('customer', 'customer'),
    ('admin', 'admin'),
)

CONST_IMAGE_TYPE = 'image'
CONST_VIDEO_TYPE = 'video'
CONST_OTHER_TYPE = 'other'
CONST_FILE_TYPE = (
    (CONST_IMAGE_TYPE, CONST_IMAGE_TYPE),
    (CONST_VIDEO_TYPE, CONST_VIDEO_TYPE),
    (CONST_OTHER_TYPE, CONST_OTHER_TYPE),
)


# Field length const
CONST_LENGTH_NAME = 160
CONST_LENGTH_NOTIFICATION_TITLE = 100
CONST_LENGTH_NOTIFICATION_BODY = 500
CONST_LENGTH_MEDIA_TYPE = 20
CONST_LENGTH_PASSWORD_MAX = 30
CONST_LENGTH_PASSWORD_MIN = 8
CONST_LENGTH_OTP_ACTION = 10
CONST_LENGTH_CONTENT_TYPE = 20
CONST_LENGTH_IMAGE_PATH = 256
CONST_LENGTH_MEDIA_URL = 1000
CONST_LENGTH_QUESTION_TYPE = 10
CONST_LENGTH_USERNAME = 20
CONST_LENGTH_USER_TYPE = 15
CONST_LENGTH_QUESTION_NAME = 1500